<a href="https://colab.research.google.com/github/sleacee/pet-projects-pandas/blob/main/Topface_test.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

financial_data - https://drive.google.com/file/d/1kSg3Ln2L7KyWk2ccniphlsqDuBZD4ytQ/view?usp=drive_link

prolongations - https://drive.google.com/file/d/1lUfXK-WML9LlNjzmI9IncQWLsM_v21wx/view?usp=drive_link

Руководитель отдела сопровождения клиентов хочет получить информацию о том, насколько хорошо сотрудники его отдела (аккаунт-менеджеры) справляются с одной из своих основных задач – пролонгацией договоров с клиентами. От аналитика он хочет получить отчет о пролонгациях сотрудников за 2023 год.

В компании используется два коэффициента пролонгации:
Для проектов пролонгированных в первый месяц – отношении суммы отгрузки проектов пролонгированных в первый месяц после завершения к сумме отгрузки последнего месяца реализации всех завершившихся в прошлом месяце проектов.
Для проектов, пролонгированных во второй месяц – отношение суммы отгрузки проектов, пролонгированных во второй месяц к сумме отгрузки последнего месяца проектов, не пролонгированных в первый.

То есть, если нам нужно понять, насколько хорошо менеджер пролонгировал в мае, необходимо посчитать:
Сумму отгрузки проектов, завершившихся в апреле (за апрель) и сумму отгрузки тех проектов завершившихся в апреле, у которых есть отгрузка в мае (за май). Коэффициент – отношение второй суммы к первой.
Сумму проектов, завершившихся в марте, у которых нет отгрузки в апреле (за март) и сумму отгрузки тех проектов, завершившихся в марте, у которых нет отгрузки в апреле но есть в мае (за май). Коэффициент – отношение второй суммы к первой.

Необходимо:
Рассчитать коэффициенты пролонгации для каждого менеджера и для всего отдела в целом
за каждый месяц и
за год
Сформировать аналитический отчет в гугл-таблицах или excel, на основании которого руководитель отдела будет принимать управленческие решения (обязательно присутствие коэффициентов пролонгации, в остальном отчет можно дополнить на свое усмотрение – дополнительные метрики и визуализация приветствуются).

In [ ]:
#подключаем используемые библиотеки и скачиваем в проект используемые csv
import pandas as pd
import numpy as np
! gdown --id 1kSg3Ln2L7KyWk2ccniphlsqDuBZD4ytQ
! gdown --id 1lUfXK-WML9LlNjzmI9IncQWLsM_v21wx

/usr/local/lib/python3.12/dist-packages/gdown/__main__.py:139: FutureWarning: Option `--id` was deprecated in version 4.3.1 and will be removed in 5.0. You don't need to pass it anymore to use a file ID.
  warnings.warn(
Downloading...
From: https://drive.google.com/uc?id=1kSg3Ln2L7KyWk2ccniphlsqDuBZD4ytQ
To: /content/financial_data.csv
100% 74.3k/74.3k [00:00<00:00, 57.6MB/s]
/usr/local/lib/python3.12/dist-packages/gdown/__main__.py:139: FutureWarning: Option `--id` was deprecated in version 4.3.1 and will be removed in 5.0. You don't need to pass it anymore to use a file ID.
  warnings.warn(
Downloading...
From: https://drive.google.com/uc?id=1lUfXK-WML9LlNjzmI9IncQWLsM_v21wx
To: /content/prolongations.csv
100% 35.7k/35.7k [00:00<00:00, 42.0MB/s]

In [ ]:
#загружаем даныне из csv
financial_data = pd.read_csv('/content/financial_data.csv')
prolongations = pd.read_csv('/content/prolongations.csv')

In [ ]:
financial_data.head(10)

,id,Причина дубля,Ноябрь 2022,Декабрь 2022,Январь 2023,Февраль 2023,Март 2023,Апрель 2023,Май 2023,Июнь 2023,Июль 2023,Август 2023,Сентябрь 2023,Октябрь 2023,Ноябрь 2023,Декабрь 2023,Январь 2024,Февраль 2024,Account
0,42,NaN,"36 220,00",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Васильев Артем Александрович
1,657,первая часть оплаты,стоп,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Васильев Артем Александрович
2,657,вторая часть оплаты,стоп,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Васильев Артем Александрович
3,594,NaN,стоп,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Васильев Артем Александрович
4,665,NaN,"10 000,00",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Васильев Артем Александрович
5,637,NaN,"38 045,00",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Соколова Анастасия Викторовна
6,419,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Михайлов Андрей Сергеевич
7,578,NaN,"82 800,00",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Попова Екатерина Николаевна
8,579,NaN,в ноль,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Васильев Артем Александрович
9,592,первая часть оплаты,"92 302,00",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Васильев Артем Александрович

In [ ]:
prolongations.head(10)

    id        month                             AM
0   42  ноябрь 2022   Васильев Артем Александрович
1  453  ноябрь 2022   Васильев Артем Александрович
2  548  ноябрь 2022      Михайлов Андрей Сергеевич
3   87  ноябрь 2022  Соколова Анастасия Викторовна
4  429  ноябрь 2022  Соколова Анастасия Викторовна
5  600  ноябрь 2022   Васильев Артем Александрович
6  657  ноябрь 2022   Васильев Артем Александрович
7  594  ноябрь 2022   Васильев Артем Александрович
8  665  ноябрь 2022   Васильев Артем Александрович
9  586  ноябрь 2022        Иванова Мария Сергеевна

In [ ]:
financial_data.columns

Index(['id', 'Причина дубля', 'Ноябрь 2022', 'Декабрь 2022', 'Январь 2023',
       'Февраль 2023', 'Март 2023', 'Апрель 2023', 'Май 2023', 'Июнь 2023',
       'Июль 2023', 'Август 2023', 'Сентябрь 2023', 'Октябрь 2023',
       'Ноябрь 2023', 'Декабрь 2023', 'Январь 2024', 'Февраль 2024',
       'Account'],
      dtype='object')

In [ ]:
#financial_data чистим от текста, nan'ов и приводим числа в нормальный вид
def clean_currency(value):
    if pd.isna(value) or str(value).strip().lower() in ['стоп', 'в ноль', '', 'end']:
        return 0.0
    clean_val = str(value).replace('\xa0', '').replace(',', '.')
    return float(clean_val)


months = ['Ноябрь 2022', 'Декабрь 2022', 'Январь 2023',
       'Февраль 2023', 'Март 2023', 'Апрель 2023', 'Май 2023', 'Июнь 2023',
       'Июль 2023', 'Август 2023', 'Сентябрь 2023', 'Октябрь 2023',
       'Ноябрь 2023', 'Декабрь 2023', 'Январь 2024', 'Февраль 2024',
       ]
for col in months:
    financial_data[col] = financial_data[col].apply(clean_currency)

In [ ]:
#поскольку причины дублей айди нас не интересуют - группируем данные из financial_data по айди и суммируем отгрузки
fin_grouped = financial_data.groupby('id')[months].sum().reset_index()
fin_grouped

,id,Ноябрь 2022,Декабрь 2022,Январь 2023,Февраль 2023,Март 2023,Апрель 2023,Май 2023,Июнь 2023,Июль 2023,Август 2023,Сентябрь 2023,Октябрь 2023,Ноябрь 2023,Декабрь 2023,Январь 2024,Февраль 2024
0,15,439280.0,439280.0,102433.75,102433.75,102433.75,138158.0,138158.0,102433.75,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0
1,16,0.0,0.0,0.00,0.00,0.00,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0
2,31,55100.0,55100.0,0.00,44775.00,44775.00,44775.0,44775.0,44775.00,44775.0,44775.0,44775.0,44775.0,44775.0,44775.00,44775.0,46200.0
3,39,137700.0,137700.0,149206.50,149206.50,149206.50,149206.5,149206.5,149206.50,149206.5,149206.5,149206.5,149206.5,149206.5,149206.50,0.0,0.0
4,42,36220.0,0.0,0.00,0.00,0.00,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
309,1001,0.0,0.0,0.00,0.00,0.00,0.0,0.0,0.00,0.0,0.0,0.0,0.0,290000.0,0.00,0.0,0.0
310,1004,0.0,0.0,0.00,0.00,0.00,0.0,0.0,0.00,0.0,0.0,0.0,0.0,34000.0,0.00,0.0,0.0
311,1006,0.0,0.0,0.00,0.00,0.00,0.0,0.0,0.00,0.0,0.0,0.0,145195.0,140495.0,140495.00,0.0,0.0
312,1012,0.0,0.0,0.00,0.00,0.00,0.0,0.0,0.00,0.0,0.0,0.0,0.0,98492.0,109442.52,0.0,0.0
313,1015,0.0,0.0,0.00,0.00,0.00,0.0,0.0,0.00,0.0,0.0,0.0,0.0,163700.0,15000.00,0.0,0.0

In [ ]:
#совмещаем данные из полученной таблицы с данными по пролонгациям
df = prolongations.merge(fin_grouped, on='id', how='left')
df

,id,month,AM,Ноябрь 2022,Декабрь 2022,Январь 2023,Февраль 2023,Март 2023,Апрель 2023,Май 2023,Июнь 2023,Июль 2023,Август 2023,Сентябрь 2023,Октябрь 2023,Ноябрь 2023,Декабрь 2023,Январь 2024,Февраль 2024
0,42,ноябрь 2022,Васильев Артем Александрович,36220.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,453,ноябрь 2022,Васильев Артем Александрович,0.0,39245.0,44320.0,177635.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,548,ноябрь 2022,Михайлов Андрей Сергеевич,674000.0,674000.0,674000.0,674000.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,87,ноябрь 2022,Соколова Анастасия Викторовна,70050.0,0.0,73380.0,83480.0,89300.0,89300.0,78605.0,72485.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,429,ноябрь 2022,Соколова Анастасия Викторовна,30280.0,35580.0,35830.0,42830.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
472,955,декабрь 2023,Смирнова Ольга Владимировна,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,9300.0,9300.0,13200.0,17400.0,0.0,0.0
473,1004,декабрь 2023,без А/М,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,34000.0,0.0,0.0,0.0
474,281,декабрь 2023,Соколова Анастасия Викторовна,98000.0,93250.0,82800.0,109000.0,125800.0,91750.0,94700.0,129740.0,117730.0,115860.0,160770.0,142490.0,99125.0,74350.0,105775.0,92065.0
475,785,декабрь 2023,Соколова Анастасия Викторовна,0.0,0.0,0.0,5306.6,12898.1,5287.0,10180.0,8600.0,3860.0,8600.0,700.0,700.0,0.0,0.0,0.0,0.0
476,913,декабрь 2023,Смирнова Ольга Владимировна,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,58200.0,58200.0,58200.0,58200.0,58200.0,58200.0,0.0,0.0

In [ ]:
#собираем список менеджеров
managers = df['AM'].unique()
managers

array(['Васильев Артем Александрович', 'Михайлов Андрей Сергеевич',
       'Соколова Анастасия Викторовна', 'Иванова Мария Сергеевна',
       'Попова Екатерина Николаевна', 'Смирнова Ольга Владимировна',
       'Кузнецов Михаил Иванович', 'без А/М', 'Петрова Анна Дмитриевна',
       'Федорова Марина Васильевна'], dtype=object)

In [ ]:
#сюда будем записывать рассчеты для каждого менеджера
result = []
#отчет за 2023 год - берем только месяца 23 года из уже созданного массива с месяцами
months_target = months[2:14]
#итератор для отслеживания 2 предыдущих месяцев
i = 0

#пройдемся по всем месяцам из таргета
for col in months_target:
  #предыдущий месяц
  prev_1 = months[i+1]
  #позапрошлый месяц
  prev_2 = months[i]

  #датафрейм с данными, где месяц пролонгации совпадает с предыдущим месяцем для рассчета первого коэффициента пролонгации
  proj_m1 = df[df['month'].str.lower() == prev_1.lower()]

  #для второго коэффициента пролонгации - сравнение месяца с позапрошлым месяцем и отсутствие отгрузки в прошлом месяце
  proj_m2 = df[(df['month'].str.lower() == prev_2.lower()) & (df[prev_1] == 0)]

  #далее в исследуемом месяце проходимся по всем менеджерам
  for am in managers:

    #фильтруем датафрейм по выбранному аккаунт-менеджеру
    am_m1 = proj_m1[proj_m1['AM'] == am]
    #в знаменатель считаем сумму отгрузок по предыдущему месяцу
    m1_sum_1 = am_m1[prev_1].sum()
    #в числитель считаем сумму отгрузок по предыдущему месяцу с учетом наличия отгрузки в текущем месяце
    m1_sum_2 = am_m1[am_m1[col] > 0][prev_1].sum()
    #из полученных значений считаем коэффициент
    cr1 = m1_sum_2 / m1_sum_1

    #аналогично для второго коэффициента
    am_m2 = proj_m2[proj_m2['AM'] == am]
    m2_sum_1 = am_m2[prev_2].sum()
    m2_sum_2 = am_m2[am_m2[col] > 0][prev_2].sum()
    cr2 = m2_sum_2 / m2_sum_1

    #добавляем посчитанные значения в список
    result.append({
      'Month' : col,
      'AM' : am,
      'CR1' : cr1,
      'CR2' : cr2,
      'To_m1' : m1_sum_1,
      'End_m1' : m1_sum_2,
      'To_m2' : m2_sum_1,
      'End_m2' : m2_sum_2,
    })
  #увеличеваем итератор на один для перехода на следующий месяц
  i+=1

/tmp/ipykernel_8787/1017977233.py:33: RuntimeWarning: invalid value encountered in scalar divide
  cr2 = m2_sum_2 / m2_sum_1
/tmp/ipykernel_8787/1017977233.py:28: RuntimeWarning: invalid value encountered in scalar divide
  cr1 = m1_sum_2 / m1_sum_1

In [ ]:
#датафрейм с результатами
res = pd.DataFrame(result)
res = res.fillna(0)

#датафрейм с значениями коэффициента за год для каждого менеджера
manager_2023 = res.groupby('AM', sort=False).agg({'To_m1': 'sum', 'End_m1': 'sum','To_m2': 'sum','End_m2': 'sum',})
manager_2023['Y_CR1'] = manager_2023['End_m1'] / manager_2023['To_m1']
manager_2023['Y_CR2'] = manager_2023['End_m2'] / manager_2023['To_m2']

#коэффициенты за год для всего отдела
total_2023_cr1 = manager_2023['End_m1'].sum() / manager_2023['To_m1'].sum()
total_2023_cr2 = manager_2023['End_m2'].sum() / manager_2023['To_m2'].sum()

#коэффициенты для всего отдела по месяцам
total_month = res.groupby('Month', sort=False).agg({'To_m1': 'sum', 'End_m1': 'sum','To_m2': 'sum','End_m2': 'sum',})
total_month['CR1'] = total_month['End_m1'] / total_month['To_m1']
total_month['CR2'] = total_month['End_m2'] / total_month['To_m2']
res

,Month,AM,CR1,CR2,To_m1,End_m1,To_m2,End_m2
0,Январь 2023,Васильев Артем Александрович,0.473548,0.000000,1693097.68,801762.68,260862.0,0.0
1,Январь 2023,Михайлов Андрей Сергеевич,0.770481,0.000000,641080.21,493940.21,41025.0,0.0
2,Январь 2023,Соколова Анастасия Викторовна,0.509922,0.648041,911513.26,464800.50,108095.0,70050.0
3,Январь 2023,Иванова Мария Сергеевна,0.464671,0.000000,2296595.71,1067160.71,52240.0,0.0
4,Январь 2023,Попова Екатерина Николаевна,0.433532,0.000000,242070.00,104945.00,82800.0,0.0
...,...,...,...,...,...,...,...,...
115,Декабрь 2023,Смирнова Ольга Владимировна,0.649101,0.388062,554051.00,359635.00,67515.0,26200.0
116,Декабрь 2023,Кузнецов Михаил Иванович,0.263085,0.000000,488381.91,128485.85,166250.0,0.0
117,Декабрь 2023,без А/М,0.000000,0.000000,0.00,0.00,0.0,0.0
118,Декабрь 2023,Петрова Анна Дмитриевна,1.000000,0.000000,98492.00,98492.00,0.0,0.0
119,Декабрь 2023,Федорова Марина Васильевна,0.000000,0.000000,0.00,0.00,0.0,0.0

In [ ]:
#выгружаем данные в эксель для формирования отчета
res.to_excel('Менеджеры по месяцам.xlsx', index=False)

In [ ]:
manager_2023.to_excel('Менеджеры за год.xlsx')

In [ ]:
total_month.to_excel('Отдел за год по месяцам.xlsx')